name = "ajnabi/jambhalaiken"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'ajnabi/jambhalaiken'"

[repository]
user = "ajnabi"
project = "jambhalaiken"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.1.0"
source = "github"
